version: "3.8"

services:
  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "3050:3050"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=3050
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
